import {$,$$,esc,icon,download,launchable,windows,createWindow,menubar,statusbar,dialog,menu,closeMenus,showDesktop,closeAll} from './ui.js';
import {openPaint} from './paint.js';
import {openMines} from './minesweeper.js';
import {launchSmith,restorePhase,getPhase} from './smith.js';
let portfolio;try{const r=await fetch('portfolio.json');if(!r.ok)throw Error(r.status);portfolio=await r.json();}catch{portfolio={intro:'Visit kfost.com to read about Kurt J. Foster.',work:[],education:[],projects:[],tools:''};}
const links=[
['Neal.fun','A delightful collection of tiny games and big ideas.','https://neal.fun/'],
['Radio Garden','Spin the globe and tune into live radio around the world.','https://radio.garden/'],
['WindowSwap','Borrow a view through someone else’s window.','https://www.window-swap.com/'],
['The Pudding','Playful, interactive stories told with data.','https://pudding.cool/'],
['Pointer Pointer','There is a photograph pointing at your cursor. Really.','https://pointerpointer.com/'],
['Zoomquilt','Fall into an endlessly zooming, hand-painted world.','https://zoomquilt.org/'],
['Little Alchemy 2','Combine simple elements and discover what happens.','https://littlealchemy2.com/'],
['Stellarium','Explore a planetarium right in your browser.','https://stellarium-web.org/'],
['Song Maker','Make a little melody, one colorful square at a time.','https://musiclab.chromeexperiments.com/Song-Maker/'],
['It’s a(door)able','A small, sweet puzzle with a surprise behind the door.','https://ncase.me/door/'],
['Chrome Experiments','A cabinet of curious experiments made for the web.','https://experiments.withgoogle.com/collection/chrome'],
['Ray Optics Simulator','Build mirrors, bend light, and play with optics.','https://phydemo.app/ray-optics/']
];
const wallpapers=[{id:'teal',name:'(None)',color:'#008080'}, {id:'clouds',name:'Clouds',file:'clouds.jpg',mode:'cover'},{id:'setup',name:'Windows 98',file:'setup.png',mode:'cover'},{id:'bubbles',name:'Bubbles',file:'bubbles.png',mode:'tile'},{id:'waves',name:'Waves',file:'waves.png',mode:'tile'},{id:'black',name:'Black',color:'#000000'}];
let wallpaper='teal',sound=false;try{wallpaper=localStorage.getItem('win98-wallpaper')||'teal';}catch{}
function applyWallpaper(id,persist=true){const wp=wallpapers.find(a=>a.id===id)||wallpapers[0];wallpaper=wp.id;const desktop=$('#desktop');desktop.style.backgroundColor=wp.color||'#008080';desktop.style.backgroundImage=wp.file?`url("assets/wallpapers/${wp.file}")`:'none';desktop.style.backgroundRepeat=wp.mode==='tile'?'repeat':'no-repeat';desktop.style.backgroundSize=wp.mode==='tile'?'auto':'cover';desktop.style.backgroundPosition='center';if(persist)try{localStorage.setItem('win98-wallpaper',wp.id);}catch{}}
const desktopItems=[{id:'portfolio',name:'Kurt J. Foster',icon:'folder',open:()=>openExplorer('home')},{id:'internet',name:'The Internet',icon:'folder',open:()=>openExplorer('internet')},{id:'smith',name:'agent_smith.exe',icon:'executable',open:launchSmith},{id:'paint',name:'Paint',icon:'paint',open:openPaint},{id:'mines',name:'Minesweeper',icon:'minesweeper',open:openMines},{id:'display',name:'Display',icon:'display',open:openDisplay}];
$('#desktop-icons').replaceChildren();for(const item of desktopItems){const el=document.createElement('button');el.className='desktop-icon';el.dataset.app=item.id;el.setAttribute('aria-label',item.name);el.title=item.name+(item.id==='smith'?' — a simulated desktop takeover':'');el.innerHTML=icon(item.icon)+`<span>${esc(item.name)}</span>`;const select=()=>{$$('.desktop-icon').forEach(b=>b.classList.remove('selected'));el.classList.add('selected');};launchable(el,item.open,select);el.oncontextmenu=e=>{e.preventDefault();select();menu(null,[{label:'Open',action:item.open},null,{label:'Properties',action:()=>dialog(item.name+' Properties',`<p><b>${esc(item.name)}</b></p><p>Type: ${['portfolio','internet'].includes(item.id)?'File Folder':'Application'}</p><p>Location: C:\\WINDOWS\\Desktop</p>`,{icon:item.icon})}],{x:e.clientX,y:e.clientY});};$('#desktop-icons').append(el);}
function readme(){return 'Kurt J. Foster\n\n'+portfolio.intro+'\n\n'+portfolio.tools+'\n\nhttps://kfost.com';}
function openNotepad(name='readme.txt',text=readme(),id='readme'){if(windows.has(id)){windows.get(id).focus();return;}const w=createWindow({id,title:name+' - Notepad',icon:'notepad',width:570,height:435,className:'notepad-window'});w.body.innerHTML='<textarea class="notepad-text sunken" spellcheck="false" aria-label="Text document"></textarea>';const input=$('textarea',w.body);input.value=text;let wrap=true;const save=()=>download(name,input.value);menubar(w,{'File':[{label:'Save as...',shortcut:'Ctrl+S',action:save},null,{label:'Exit',action:w.close}],'Edit':[{label:'Select All',shortcut:'Ctrl+A',action:()=>{input.focus();input.select();}},{label:'Time/Date',shortcut:'F5',action:()=>{input.setRangeText(new Date().toLocaleString(),input.selectionStart,input.selectionEnd,'end');input.focus();}}],'Format':()=>[{label:'Word Wrap',checked:wrap,action:()=>{wrap=!wrap;input.style.whiteSpace=wrap?'pre-wrap':'pre';input.wrap=wrap?'soft':'off';}}],'Help':[{label:'About Notepad',action:()=>dialog('About Notepad','<p><b>Windows 98 Notepad</b></p><p>Read and edit text. File → Save as keeps a copy on your device.</p>',{icon:'notepad'})}]});w.el.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();}if(e.key==='F5'){e.preventDefault();input.setRangeText(new Date().toLocaleString(),input.selectionStart,input.selectionEnd,'end');}});statusbar(w,'<span>Text document</span><span>UTF-8</span>');}
function entryView(entry){const id=entry.id;if(windows.has(id)){windows.get(id).focus();return;}const w=createWindow({id,title:entry.title,icon:entry.id.startsWith('projects')?'folder-open':'document',width:650,height:545,className:'document-window'});w.body.innerHTML=`<article class="portfolio-document sunken"><div class="document-heading">${entry.image?`<img src="${esc(entry.image)}" alt="${esc(entry.title)}" loading="lazy">`:''}<div><h1>${esc(entry.title)}</h1><p>${esc(entry.company)}</p><p>${esc(entry.date||entry.status)}</p></div></div><div class="document-details">${entry.html}</div></article>`;menubar(w,{'File':[{label:'View on kfost.com',action:()=>window.open('https://kfost.com/#'+(id.startsWith('work')?'work':id.startsWith('education')?'education':'projects'),'_blank','noopener,noreferrer')},null,{label:'Close',action:w.close}],'Help':[{label:'About this document',action:()=>dialog('Document Properties','<p>Portfolio content from <a href="https://kfost.com/" target="_blank" rel="noopener">kfost.com</a>.</p><p>Project files open in a new browser tab.</p>')}]});statusbar(w,'<span>Source: kfost.com</span><span>My Documents</span>');}
const descriptions={home:['Kurt J. Foster','Automation & equipment maintenance.','Explore my work, education, and things I’ve built.'],work:['Work History','Manufacturing. Maintenance. Automation.','Nine roles, from custom equipment to high-volume production.'],education:['Education','Linn-Benton Community College','Industrial Automation Technology · Class of 2018'],projects:['Projects','Electrical & mechanical projects','Open documentation, schematics, and CAD files.'],internet:['The Internet','A few good rabbit holes.','Double-click a shortcut to venture out. Links open in a new tab.']};
function openExplorer(start='home'){const id=start==='internet'?'internet':'explorer';if(windows.has(id)){windows.get(id).focus();if(start!=='home')windows.get(id).navigate(start);return;}const w=createWindow({id,title:descriptions[start][0],icon:'folder',width:714,height:455,className:'explorer-window',x:Math.max(112,(innerWidth-714)/2+20),y:Math.max(55,(innerHeight-455)/3)});let path=start,history=[start],index=0,view='icons',selected=null,items=[];
const bars=document.createElement('div');bars.className='explorer-bars';bars.innerHTML='<div class="toolbar"><button class="back-tool" aria-label="Back"><b>←</b><span>Back</span></button><button class="forward-tool" aria-label="Forward"><b>→</b></button><button class="up-tool" aria-label="Up one level"><b>↑</b><span>Up</span></button><span class="toolbar-divider"></span><button class="view-tool">▦<span>Views</span></button></div><div class="addressbar"><span>Address</span><div class="address-value sunken"></div><button class="go-address raised" aria-label="Open current folder">Go</button></div>';w.el.insertBefore(bars,w.body);
w.body.innerHTML='<div class="folder-body sunken"><aside class="folder-sidebar"></aside><div class="folder-files"></div></div>';const foot=statusbar(w,'<span class="object-count"></span><span>'+icon('computer',16)+' My Computer</span>');
function navigate(next,push=true){path=next;selected=null;if(push){history=history.slice(0,index+1);history.push(next);index++;}render();}w.navigate=navigate;
function selectAll(){selected='all';$$('.file-icon',w.body).forEach(b=>b.classList.add('selected'));$('.object-count',foot).textContent=items.length+' objects selected';}
function goBack(){if(index>0)navigate(history[--index],false);}function goForward(){if(index<history.length-1)navigate(history[++index],false);}
function buildItems(){if(path==='home')return [{name:'Work History',icon:'folder',type:'File Folder',desc:'9 work history documents',open:()=>navigate('work')},{name:'Education',icon:'folder',type:'File Folder',desc:'Completed education',open:()=>navigate('education')},{name:'Projects',icon:'folder',type:'File Folder',desc:'6 electrical and mechanical projects',open:()=>navigate('projects')},{name:'readme.txt',icon:'file',type:'Text Document',desc:'A little about Kurt J. Foster',open:()=>openNotepad()}];if(path==='internet')return links.map(([name,desc,url])=>({name,desc,url,icon:'globe',type:'Internet Shortcut',open:()=>window.open(url,'_blank','noopener,noreferrer')}));return portfolio[path].map(a=>({name:path==='work'?a.company.split(' ·')[0]+' ('+(a.date.match(/\d{4}/)||[''])[0]+')':a.title,icon:path==='projects'?'folder':'file',type:path==='projects'?'Project Folder':'Text Document',desc:path==='work'?a.title:a.company,open:()=>entryView(a)}));}
function render(){const [title,sub,desc]=descriptions[path];w.setTitle(title);items=buildItems();$('.folder-sidebar',w.body).innerHTML=icon(path==='internet'?'globe':'folder-open')+`<h1>${esc(title)}</h1><hr><p><b>${esc(sub)}</b></p><p class="folder-description">${esc(desc)}</p>${path==='home'?'<a class="readme-link" href="#readme">Read about me →</a>':''}`;$('.readme-link',w.body)?.addEventListener('click',e=>{e.preventDefault();openNotepad();});$('.address-value',bars).innerHTML=icon('folder',16)+'<span>C:\\WINDOWS\\Desktop\\'+(path==='internet'?'The Internet':'Kurt J. Foster'+(path==='home'?'':'\\'+title))+'</span>';
const host=$('.folder-files',w.body);host.className='folder-files '+(view==='details'?'details-view':'icon-view');host.replaceChildren();if(view==='details')host.insertAdjacentHTML('beforeend','<div class="detail-columns"><span>Name</span><span>Type</span></div>');items.forEach((item,i)=>{const b=document.createElement('button');b.className='file-icon';b.innerHTML=icon(item.icon)+`<span>${esc(item.name)}</span>${view==='details'?`<small>${esc(item.type)}</small>`:''}`;b.title=item.desc;b.setAttribute('aria-label',item.name);launchable(b,item.open,()=>{selected=i;$$('.file-icon',host).forEach(el=>el.classList.remove('selected'));b.classList.add('selected');$('.folder-description',w.body).textContent=item.desc;$('.object-count',foot).textContent='1 object selected';});host.append(b);});$('.object-count',foot).textContent=items.length+' object(s)';$('.back-tool',bars).disabled=index===0;$('.forward-tool',bars).disabled=index===history.length-1;$('.up-tool',bars).disabled=path==='home'||path==='internet';}
$('.back-tool',bars).onclick=goBack;$('.forward-tool',bars).onclick=goForward;$('.up-tool',bars).onclick=()=>navigate('home');$('.go-address',bars).onclick=()=>render();$('.view-tool',bars).onclick=e=>menu(e.currentTarget,[{label:'Large Icons',checked:view==='icons',action:()=>{view='icons';render();}},{label:'Details',checked:view==='details',action:()=>{view='details';render();}}]);
menubar(w,{'File':()=>[{label:'Open',disabled:selected===null,action:()=>selected==='all'?items.forEach(a=>a.open()):items[selected]?.open()},null,{label:'Close',action:w.close}],'Edit':[{label:'Select All',shortcut:'Ctrl+A',action:selectAll}],'View':()=>[{label:'Large Icons',checked:view==='icons',action:()=>{view='icons';render();}},{label:'Details',checked:view==='details',action:()=>{view='details';render();}},null,{label:'Refresh',action:render}],'Go':()=>[{label:'Back',disabled:index===0,action:goBack},{label:'Forward',disabled:index===history.length-1,action:goForward},{label:'Up One Level',disabled:path==='home'||path==='internet',action:()=>navigate('home')},{label:'Kurt J. Foster',action:()=>openExplorer('home')}],'Favorites':[{label:'The Internet',action:()=>openExplorer('internet')},{label:'kfost.com',action:()=>window.open('https://kfost.com/','_blank','noopener,noreferrer')}],'Help':[{label:'Windows Help',action:openHelp},{label:'About Windows 98',action:openAbout}]});w.el.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selectAll();}if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();goBack();}if(e.altKey&&e.key==='ArrowUp'&&path!=='home'&&path!=='internet'){e.preventDefault();navigate('home');}});render();}
function openDisplay(){if(windows.has('display')){windows.get('display').focus();return;}const w=createWindow({id:'display',title:'Display Properties',icon:'display',width:430,height:490,className:'display-window',resizable:false});let chosen=wallpaper;w.body.innerHTML='<div class="property-tabs"><button class="property-tab active">Background</button><button class="property-tab">Appearance</button></div><div class="property-panel raised"><div class="background-panel"><div class="monitor"><div class="monitor-screen"></div><div class="monitor-lights"><i></i></div></div><p>Select a wallpaper for your desktop.</p><label>Wallpaper:<select class="wallpaper-list sunken" size="6" aria-label="Wallpaper">'+wallpapers.map(wp=>`<option value="${wp.id}" ${wp.id===chosen?'selected':''}>${wp.name}</option>`).join('')+'</select></label></div><div class="appearance-panel" hidden><p><b>Windows Standard</b></p><div class="raised appearance-sample"><div class="titlebar">Active Window</div><p>Window text</p><button class="raised standard-button">OK</button></div><p>Classic silver controls, blue title bars, and the original desktop typeface.</p><p>Desktop icons open with a double-click. On touchscreens, tap once.</p></div></div><div class="display-buttons"><button class="raised standard-button display-ok">OK</button><button class="raised standard-button display-cancel">Cancel</button><button class="raised standard-button display-apply">Apply</button></div>';
function preview(){const wp=wallpapers.find(a=>a.id===chosen),screen=$('.monitor-screen',w.body);screen.style.backgroundColor=wp.color||'#008080';screen.style.backgroundImage=wp.file?`url(assets/wallpapers/${wp.file})`:'none';screen.style.backgroundSize=wp.mode==='tile'?'32px':'cover';screen.style.backgroundRepeat=wp.mode==='tile'?'repeat':'no-repeat';screen.style.backgroundPosition='center';screen.innerHTML='<div class="mini-window"><div></div></div><div class="mini-taskbar"></div>';}$('select',w.body).onchange=e=>{chosen=e.target.value;preview();};$('.display-apply',w.body).onclick=()=>applyWallpaper(chosen);$('.display-ok',w.body).onclick=()=>{applyWallpaper(chosen);w.close();};$('.display-cancel',w.body).onclick=w.close;$$('.property-tab',w.body).forEach((b,i)=>b.onclick=()=>{$$('.property-tab',w.body).forEach(el=>el.classList.remove('active'));b.classList.add('active');$('.background-panel',w.body).hidden=i!==0;$('.appearance-panel',w.body).hidden=i!==1;});$('.appearance-sample button',w.body).onclick=()=>{$$('.property-tab',w.body)[0].click();};preview();}
function openHelp(){dialog('Windows Help','<h3>Welcome to your desktop</h3><p><b>Open:</b> double-click an icon, or select it and press Enter. On a touchscreen, tap once.</p><p><b>Windows:</b> drag the title bar to move. Use the corner to resize. Minimize to the taskbar; click the task to return.</p><p><b>Try:</b> make a drawing in Paint, clear a minefield, or change your wallpaper in Display.</p><p><b>agent_smith.exe:</b> a fictional takeover with a way back home. Escape skips the animation.</p>',{icon:'help',width:480});}
function openAbout(){dialog('About Windows 98','<div class="about-wordmark"><b>Microsoft</b><br>Windows<span>98</span></div><p>Microsoft Windows 98<br>Second Edition · 4.10.2222 A</p><p>Registered to:<br><b>Kurt J. Foster</b></p><hr><p>An interactive desktop tribute. Original Windows artwork belongs to Microsoft.</p>',{icon:'computer',width:460});}
function startMenu(){if($('#start-menu')){closeMenus();return;}closeMenus();$('#start-button').classList.add('pressed');const m=document.createElement('div');m.id='start-menu';m.className='start-menu raised';m.innerHTML='<div class="start-side"><span>Windows<b>98</b></span></div><div class="start-options"></div>';const host=$('.start-options',m);const entries=[['folder','Kurt J. Foster',()=>openExplorer('home')],['globe','The Internet',()=>openExplorer('internet')],null,['paint','Paint',openPaint],['minesweeper','Minesweeper',openMines],['notepad','readme.txt',()=>openNotepad()],null,['settings','Settings',openDisplay],['help','Help',openHelp],['run','Run...',openRun],null,['shutdown','Shut Down...',openShutdown]];for(const a of entries){if(!a){host.insertAdjacentHTML('beforeend','<div class="menu-separator"></div>');continue;}const b=document.createElement('button');b.innerHTML=icon(a[0])+`<span>${esc(a[1])}</span>`;b.onclick=()=>{closeMenus();a[2]();};host.append(b);}$('#menus').append(m);$('button',host).focus();m.onkeydown=e=>{const a=$$('button',host),i=a.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();a[(i+(e.key==='ArrowDown'?1:-1)+a.length)%a.length]?.focus();}};}
function openRun(){const w=createWindow({id:'run',title:'Run',icon:'run',width:410,height:200,className:'message-window',resizable:false});w.body.innerHTML='<div class="run-body"><p>Type the name of a program, and Windows will open it for you.</p><label>Open: <input class="sunken" aria-label="Program name" placeholder="mspaint, winmine, notepad..."></label><div class="dialog-buttons"><button class="raised standard-button run-ok">OK</button><button class="raised standard-button run-cancel">Cancel</button></div></div>';const input=$('input',w.body);const run=()=>{const c=input.value.toLowerCase().trim().replace(/\.exe$/,'');const fn={mspaint:openPaint,paint:openPaint,winmine:openMines,minesweeper:openMines,notepad:()=>openNotepad(),explorer:()=>openExplorer('home'),control:openDisplay,agent_smith:launchSmith}[c];if(fn){w.close();fn();}else dialog('Run','<p>Windows cannot find “'+esc(input.value)+'”. Try mspaint, winmine, notepad, explorer, control, or agent_smith.exe.</p>');};$('.run-ok',w.body).onclick=run;$('.run-cancel',w.body).onclick=w.close;input.onkeydown=e=>{if(e.key==='Enter')run();};input.focus();}
function openShutdown(){dialog('Shut Down Windows','<p>Are you sure you want to restart the desktop?</p>',{icon:'shutdown',buttons:[['Restart',()=>{closeAll();openExplorer('home');}],['Cancel',null]]});}
$('#start-button').onclick=startMenu;$('#show-desktop').innerHTML=icon('computer',16);$('#show-desktop').onclick=showDesktop;$('.flag-logo').outerHTML='<img class="start-logo" src="assets/icons/start-logo.png" width="20" height="20" alt="">';
$('#sound-toggle').onclick=()=>{sound=!sound;$('#sound-toggle').textContent=sound?'♫':'♪';$('#sound-toggle').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('#sound-toggle').title=sound?'Sound on':'Sound off';$('#sound-toggle').classList.toggle('sound-on',sound);if(sound)beep();};document.addEventListener('win98-open',()=>{if(sound)beep();});function beep(){try{const ctx=new(window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=660;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.2);o.onended=()=>ctx.close();}catch{}}
function tick(){$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('#tray').title=new Date().toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'});}tick();setInterval(tick,1000);
$('#desktop').addEventListener('pointerdown',e=>{if(e.target.id==='desktop')$$('.desktop-icon').forEach(b=>b.classList.remove('selected'));});$('#desktop').addEventListener('contextmenu',e=>{if(e.target.closest('.window,.desktop-icon'))return;e.preventDefault();menu(null,[{label:'Arrange Icons',action:()=>{$('#desktop-icons').classList.toggle('horizontal-icons');}},{label:'Refresh',action:()=>applyWallpaper(wallpaper,false)},null,{label:'Properties',action:openDisplay}],{x:e.clientX,y:e.clientY});});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Escape'&&getPhase()==='desktop'){e.preventDefault();startMenu();}});document.addEventListener('desktop-reset',()=>{applyWallpaper('teal');$$('.desktop-icon').forEach(b=>b.classList.remove('selected'));$('#desktop-icons').classList.remove('horizontal-icons');openExplorer('home');});
applyWallpaper(wallpaper,false);openExplorer('home');restorePhase();
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const registrations=[{name:'get_desktop_state',title:'Read desktop state',description:'Read open applications, current wallpaper, and the desktop simulation phase.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({windows:[...windows.values()].map(w=>({title:w.title,minimized:w.minimized})),wallpaper,phase:getPhase()})},{name:'open_desktop_application',title:'Open desktop application',description:'Open a desktop folder, Paint, Minesweeper, Notepad, or Display Properties. Does not run Agent Smith.',inputSchema:{type:'object',properties:{app:{type:'string',enum:['portfolio','internet','paint','minesweeper','notepad','display']}},required:['app'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const actions={portfolio:()=>openExplorer('home'),internet:()=>openExplorer('internet'),paint:openPaint,minesweeper:openMines,notepad:()=>openNotepad(),display:openDisplay};if(!input||Object.keys(input).some(k=>k!=='app')||!Object.hasOwn(actions,input.app))throw Error('Unknown desktop application');if(getPhase()!=='desktop')throw Error('Recover the desktop before opening an application');actions[input.app]();return {opened:input.app};}},{name:'set_desktop_wallpaper',title:'Set desktop wallpaper',description:'Apply and remember a Windows 98 wallpaper on this device.',inputSchema:{type:'object',properties:{wallpaper:{type:'string',enum:wallpapers.map(w=>w.id)}},required:['wallpaper'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||Object.keys(input).some(k=>k!=='wallpaper')||!wallpapers.some(w=>w.id===input.wallpaper))throw Error('Unknown wallpaper');applyWallpaper(input.wallpaper);return {wallpaper};}}];for(const tool of registrations)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
