import {$,$$,createWindow,windows,menubar,statusbar,dialog,icon} from './ui.js';
export function mineNeighbors(i,cols,rows){const x=i%cols,y=Math.floor(i/cols),a=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const xx=x+dx,yy=y+dy;if(xx>=0&&xx<cols&&yy>=0&&yy<rows)a.push(yy*cols+xx);}return a;}
export function makeBoard(cols,rows,count,first,random=Math.random){const safe=new Set([first,...mineNeighbors(first,cols,rows)]),spots=Array.from({length:cols*rows},(_,i)=>i).filter(i=>!safe.has(i));for(let i=spots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[spots[i],spots[j]]=[spots[j],spots[i]];}const bombs=new Set(spots.slice(0,count));return Array.from({length:cols*rows},(_,i)=>({mine:bombs.has(i),n:mineNeighbors(i,cols,rows).filter(j=>bombs.has(j)).length,open:false,flag:false}));}
export function reveal(board,i,cols,rows){if(board[i].flag||board[i].open)return false;if(board[i].mine){board[i].open=true;return true;}const q=[i];while(q.length){const j=q.pop(),c=board[j];if(c.open||c.flag||c.mine)continue;c.open=true;if(!c.n)q.push(...mineNeighbors(j,cols,rows).filter(k=>!board[k].open&&!board[k].flag&&!board[k].mine));}return false;}
const levels={Beginner:[8,8,10],Intermediate:[16,16,40],Expert:[30,16,99]};
const face=state=>`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="#ffff00" stroke="#000" stroke-width="1.5"/>${state==='won'?'<path d="M4 8h16M5 8l2 5h3l2-5 2 5h3l2-5" fill="#000"/>':state==='lost'?'<path d="m7 7 3 3m0-3-3 3m7-3 3 3m0-3-3 3" stroke="#000" stroke-width="1.4"/>':'<path d="M8 7v3m8-3v3" stroke="#000" stroke-width="2"/>'}<path d="${state==='lost'?'M7 18q5-6 10 0':'M6 14q6 8 12 0'}" fill="none" stroke="#000" stroke-width="1.5"/></svg>`;
export function openMines(){if(windows.has('mines')){windows.get('mines').focus();return;}const w=createWindow({id:'mines',title:'Minesweeper',icon:'minesweeper',width:288,height:384,className:'mines-window',resizable:false});let level='Beginner',cols,rows,count,board,state='ready',seconds=0,flagMode=false,timer=null;
menubar(w,{'Game':()=>[{label:'New',shortcut:'F2',action:reset},null,...Object.keys(levels).map(l=>({label:l,checked:level===l,action:()=>{level=l;reset();}})),null,{label:'Exit',action:w.close}],'Help':[{label:'How to play',action:()=>dialog('Minesweeper Help','<p>Uncover every square without a mine. Numbers tell you how many mines touch that square.</p><p>Right-click to flag a mine. On touchscreens, use Flag mode. Click a revealed number to clear its neighbors when you have placed enough flags.</p><p>Your first click is always safe. Click the smiley face or press F2 for a new game.</p>')} ]});
w.body.innerHTML=`<div class="mine-surface raised"><div class="mine-header sunken"><output class="led" id="mine-counter" aria-label="Mines remaining">010</output><button class="raised mine-face" aria-label="New game">${face('ready')}</button><output class="led" id="mine-time" aria-label="Elapsed seconds">000</output></div><div class="mine-board-wrap"><div class="mine-board sunken" role="group" aria-label="Minefield"></div></div></div><div class="mine-controls"><button class="raised flag-toggle" aria-pressed="false">⚑ Flag mode</button><span class="mine-state" aria-live="polite">Find 10 mines.</span></div>`;
const grid=$('.mine-board',w.body),counter=$('#mine-counter',w.body),clock=$('#mine-time',w.body),smile=$('.mine-face',w.body),msg=$('.mine-state',w.body);
function reset(){clearInterval(timer);[cols,rows,count]=levels[level];seconds=0;state='ready';board=Array.from({length:cols*rows},()=>({open:false,flag:false,mine:false,n:0}));flagMode=false;$('.flag-toggle',w.body).setAttribute('aria-pressed','false');$('.flag-toggle',w.body).classList.remove('sunken');grid.style.gridTemplateColumns=`repeat(${cols},var(--cell))`;w.el.style.width=Math.min(cols*26+66,innerWidth-12)+'px';w.el.style.height=Math.min(rows*26+222,innerHeight-60)+'px';grid.replaceChildren();board.forEach((c,i)=>{const b=document.createElement('button');b.className='mine-cell';b.dataset.index=i;b.setAttribute('aria-label',`Row ${Math.floor(i/cols)+1}, column ${i%cols+1}, covered`);b.onclick=()=>flagMode?flag(i):click(i);b.oncontextmenu=e=>{e.preventDefault();flag(i);};b.onkeydown=e=>{if(e.key==='f'||e.key==='F'){e.preventDefault();flag(i);}const moves={ArrowRight:1,ArrowLeft:-1,ArrowUp:-cols,ArrowDown:cols};if(moves[e.key]){e.preventDefault();grid.children[Math.max(0,Math.min(board.length-1,i+moves[e.key]))]?.focus();}};grid.append(b);});render();}
function flag(i){if(state==='lost'||state==='won'||board[i].open)return;board[i].flag=!board[i].flag;render();}
function click(i){if(state==='lost'||state==='won'||board[i].flag)return;if(state==='ready'){const flags=board.map(c=>c.flag);board=makeBoard(cols,rows,count,i);board.forEach((c,j)=>c.flag=flags[j]);state='playing';timer=setInterval(()=>{seconds=Math.min(999,seconds+1);clock.textContent=String(seconds).padStart(3,'0');},1000);}let hit=false;if(board[i].open){const n=mineNeighbors(i,cols,rows);if(n.filter(j=>board[j].flag).length===board[i].n)for(const j of n)if(!board[j].flag)hit=reveal(board,j,cols,rows)||hit;}else hit=reveal(board,i,cols,rows);if(hit){state='lost';clearInterval(timer);}else if(board.every(c=>c.mine||c.open)){state='won';clearInterval(timer);board.forEach(c=>{if(c.mine)c.flag=true;});}render();}
function render(){const remaining=count-board.filter(c=>c.flag).length;counter.textContent=remaining<0?'-'+String(Math.min(99,-remaining)).padStart(2,'0'):String(remaining).padStart(3,'0');clock.textContent=String(seconds).padStart(3,'0');smile.innerHTML=face(state);msg.textContent=state==='won'?'You win! Nicely done.':state==='lost'?'Boom! Try again.':flagMode?'Tap a square to flag it.':`${level} · ${count} mines`;
board.forEach((c,i)=>{const b=grid.children[i],show=c.open||(state==='lost'&&c.mine);b.className='mine-cell '+(show?'revealed ':'')+(c.open&&c.mine?'exploded ':'')+(c.flag?'flagged':'');b.style.color=['','#0000ff','#008000','#ff0000','#000080','#800000','#008080','#000','#808080'][c.n];b.innerHTML=show?(c.mine?icon('minesweeper',16):c.n||''):c.flag?'⚑':'';if(state==='lost'&&c.flag&&!c.mine){b.textContent='×';b.classList.add('wrong-flag');}b.setAttribute('aria-label',`Row ${Math.floor(i/cols)+1}, column ${i%cols+1}, ${show?(c.mine?'mine':c.n+' neighboring mines'):c.flag?'flagged':'covered'}`);});}
smile.onclick=reset;$('.flag-toggle',w.body).onclick=e=>{flagMode=!flagMode;e.currentTarget.classList.toggle('sunken',flagMode);e.currentTarget.setAttribute('aria-pressed',String(flagMode));render();};w.el.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();reset();}});w.cleanup=()=>clearInterval(timer);reset();}
