import {$,$$,createWindow,windows,menubar,statusbar,dialog,download} from './ui.js';
const toolPaths={pencil:'M5 20 8 13 18 3 22 7 12 17z M8 13l4 4 M17 4l4 4',brush:'M6 16 16 3 21 7 10 19 M10 19c-1 4-6 4-8 3 3-1 0-6 4-6z',eraser:'m4 15 10-11 9 8-10 11H9z M9 10l9 8',fill:'m4 10 9-8 10 9-10 10z M4 10h19 M6 3l9 9 M21 16c-4 5-3 7 0 7s4-2 0-7',picker:'m6 19 8-8 M12 5l8 8 M14 7l5-5 4 4-5 5 M3 22l4-8 3 3z',spray:'M3 7h5v14H3z M4 3h3v4 M9 3h1 M13 2h1 M16 4h1 M11 8h1 M17 10h1 M21 2h1 M22 7h1 M19 15h1 M13 13h1',text:'M4 21 12 3 20 21 M7 15h10 M1 21h7 M16 21h7',line:'M3 21 21 3',rectangle:'M3 5h19v15H3z',ellipse:'M22 12c0 5-4 9-10 9S2 17 2 12s4-9 10-9 10 4 10 9',rounded:'M7 4h11q4 0 4 4v9q0 4-4 4H7q-4 0-4-4V8q0-4 4-4',select:'M3 3h3m3 0h3m3 0h3m3 0v3m0 3v3m0 3v3m0 3h-3m-3 0h-3m-3 0H6m-3 0v-3m0-3v-3m0-3V6'};
const names={pencil:'Pencil',brush:'Brush',eraser:'Eraser',fill:'Fill with color',picker:'Pick color',spray:'Airbrush',text:'Text',line:'Line',rectangle:'Rectangle',ellipse:'Ellipse',rounded:'Rounded rectangle',select:'Rectangular selection'};
const palette=['#000000','#808080','#800000','#808000','#008000','#008080','#000080','#800080','#808040','#004040','#0080ff','#004080','#8000ff','#804000','#ffffff','#c0c0c0','#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff','#ffff80','#00ff80','#80ffff','#8080ff','#ff0080','#ff8040'];
export function floodFill(ctx,x,y,hex){const {width,height}=ctx.canvas;x=Math.max(0,Math.min(width-1,Math.floor(x)));y=Math.max(0,Math.min(height-1,Math.floor(y)));const img=ctx.getImageData(0,0,width,height),d=img.data,at=(y*width+x)*4,old=[...d.slice(at,at+4)],n=[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16),255];if(old.every((v,i)=>v===n[i]))return;const q=[y*width+x],match=p=>old.every((v,j)=>d[p*4+j]===v);while(q.length){const p=q.pop();if(!match(p))continue;for(let j=0;j<4;j++)d[p*4+j]=n[j];const xx=p%width,yy=Math.floor(p/width);if(xx)q.push(p-1);if(xx<width-1)q.push(p+1);if(yy)q.push(p-width);if(yy<height-1)q.push(p+width);}ctx.putImageData(img,0,0);}
export function openPaint(){if(windows.has('paint')){windows.get('paint').focus();return;}const w=createWindow({id:'paint',title:'untitled - Paint',icon:'paint',width:880,height:620,className:'paint-window'});let tool='pencil',color='#000000',secondary='#ffffff',size=3,fillShape=false,drawing=false,start=null,previous=null,before=null,history=[],future=[],selection=null,sprayTimer=null;
w.body.innerHTML=`<div class="paint-workspace"><aside class="paint-tools" aria-label="Drawing tools"><div class="tool-grid">${Object.keys(names).map(t=>`<button class="raised paint-tool ${t==='pencil'?'chosen':''}" data-tool="${t}" title="${names[t]}" aria-label="${names[t]}" aria-pressed="${t==='pencil'}"><svg viewBox="0 0 26 26" aria-hidden="true"><path d="${toolPaths[t]}" fill="${['eraser','fill'].includes(t)?'#ffff80':'none'}" stroke="#000" stroke-width="1.4" stroke-linejoin="round"/></svg></button>`).join('')}</div><label class="brush-label">Size<select aria-label="Brush size"><option value="1">1 px</option><option value="3" selected>3 px</option><option value="6">6 px</option><option value="12">12 px</option><option value="24">24 px</option></select></label><label class="fill-shape"><input type="checkbox"> Fill</label></aside><div class="paint-scroll sunken"><canvas width="800" height="450" aria-label="Paint drawing canvas" tabindex="0"></canvas></div></div><div class="paint-palette"><div class="current-colors sunken"><span class="secondary-color"></span><span class="primary-color"></span></div><div class="swatches">${palette.map(c=>`<button class="swatch sunken" style="background:${c}" data-color="${c}" aria-label="Choose ${c}" title="${c}"></button>`).join('')}</div><label class="custom-color" title="Choose a custom color"><input type="color" value="#000000" aria-label="Custom color"></label></div>`;
const canvas=$('canvas',w.body),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);const status=statusbar(w,'<span class="paint-status">For Help, click Help Topics on the Help Menu.</span><span class="coordinates">800 × 450 px</span>');
function snapshot(){history.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(history.length>20)history.shift();future=[];}
function undo(){if(!history.length)return;future.push(ctx.getImageData(0,0,canvas.width,canvas.height));ctx.putImageData(history.pop(),0,0);}
function redo(){if(!future.length)return;history.push(ctx.getImageData(0,0,canvas.width,canvas.height));ctx.putImageData(future.pop(),0,0);}
function clear(){snapshot();ctx.fillStyle=secondary;ctx.fillRect(0,0,canvas.width,canvas.height);selection=null;}
function save(){const data=canvas.toDataURL('image/png');const saved=createWindow({id:'paint-save',title:'Save Picture',icon:'paint',width:420,height:330,className:'save-picture-window'});saved.body.innerHTML='<div class="save-picture"><img alt="Your drawing, ready to save" src="'+data+'"><p>untitled.png · 800 × 450 pixels</p><a class="raised standard-button save-image-link" href="'+data+'" download="untitled.png">Download PNG</a><p class="save-hint">On mobile, you can also touch and hold the picture to save it.</p></div>';$('.paint-status',status).textContent='Picture ready to save';}
function choose(t){tool=t;selection=null;$$('[data-tool]',w.body).forEach(b=>{b.classList.toggle('chosen',b.dataset.tool===t);b.setAttribute('aria-pressed',String(b.dataset.tool===t));});$('.paint-status',status).textContent=names[t]+(t==='select'?' — drag a selection, then press Delete.':t==='text'?' — click the canvas to add text.':'');canvas.style.cursor=t==='picker'?'crosshair':t==='text'?'text':'crosshair';}
function colors(){$('.primary-color',w.body).style.background=color;$('.secondary-color',w.body).style.background=secondary;$('input[type=color]',w.body).value=color;}
$$('[data-tool]',w.body).forEach(b=>b.onclick=()=>choose(b.dataset.tool));$$('[data-color]',w.body).forEach(b=>{b.onclick=()=>{color=b.dataset.color;colors();};b.oncontextmenu=e=>{e.preventDefault();secondary=b.dataset.color;colors();};});$('select',w.body).onchange=e=>size=+e.target.value;$('input[type=checkbox]',w.body).onchange=e=>fillShape=e.target.checked;$('input[type=color]',w.body).oninput=e=>{color=e.target.value;colors();};
const pos=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};};
function textAt(p){const d=createWindow({title:'Paint — Text',icon:'paint',width:350,height:200,className:'message-window',resizable:false});d.body.innerHTML='<div class="paint-text-dialog"><label>Enter text:<input class="sunken" aria-label="Text to draw" maxlength="200"></label><button class="raised standard-button">Draw text</button></div>';const input=$('input',d.body);function commit(){if(input.value){snapshot();ctx.fillStyle=color;ctx.font=`${Math.max(16,size*4)}px Arial`;ctx.fillText(input.value,p.x,p.y+Math.max(16,size*4));}d.close();}$('button',d.body).onclick=commit;input.onkeydown=e=>{if(e.key==='Enter')commit();};input.focus();}
function stroke(a,b,button=0){ctx.strokeStyle=tool==='eraser'?secondary:button===2?secondary:color;ctx.lineWidth=tool==='eraser'?size*5:tool==='pencil'?Math.max(1,size):size*2;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
function spray(p){ctx.fillStyle=color;for(let i=0;i<16;i++){const a=Math.random()*Math.PI*2,r=Math.sqrt(Math.random())*size*4;ctx.fillRect(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,1,1);}}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{e.preventDefault();canvas.focus();const p=pos(e);if(tool==='picker'){const px=ctx.getImageData(Math.min(canvas.width-1,Math.floor(p.x)),Math.min(canvas.height-1,Math.floor(p.y)),1,1).data;color='#'+[...px].slice(0,3).map(n=>n.toString(16).padStart(2,'0')).join('');colors();choose('pencil');return;}if(tool==='text'){textAt(p);return;}snapshot();before=ctx.getImageData(0,0,canvas.width,canvas.height);if(tool==='fill'){floodFill(ctx,p.x,p.y,e.button===2?secondary:color);return;}drawing=true;start=p;previous=p;canvas.setPointerCapture(e.pointerId);if(['pencil','brush','eraser'].includes(tool))stroke(p,{x:p.x+.01,y:p.y},e.button);if(tool==='spray'){spray(p);sprayTimer=setInterval(()=>spray(previous),35);}};
canvas.onpointermove=e=>{const p=pos(e);$('.coordinates',status).textContent=`${Math.round(p.x)}, ${Math.round(p.y)} px`;if(!drawing)return;if(['pencil','brush','eraser'].includes(tool))stroke(previous,p,e.buttons===2?2:0);else if(tool!=='spray'){ctx.putImageData(before,0,0);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=size;ctx.lineCap='butt';ctx.beginPath();let x=Math.min(start.x,p.x),y=Math.min(start.y,p.y),ww=Math.abs(p.x-start.x),hh=Math.abs(p.y-start.y);if(tool==='line'){ctx.moveTo(start.x,start.y);ctx.lineTo(p.x,p.y);}if(tool==='rectangle'||tool==='select')ctx.rect(x,y,ww,hh);if(tool==='rounded')ctx.roundRect(x,y,ww,hh,Math.min(10,ww/2,hh/2));if(tool==='ellipse')ctx.ellipse(x+ww/2,y+hh/2,ww/2,hh/2,0,0,Math.PI*2);if(tool==='select'){ctx.setLineDash([3,3]);ctx.strokeStyle='#666';ctx.lineWidth=1;selection={x,y,w:ww,h:hh};}if(fillShape&&['rectangle','rounded','ellipse'].includes(tool))ctx.fill();ctx.stroke();ctx.setLineDash([]);}previous=p;};
function end(){if(!drawing)return;drawing=false;clearInterval(sprayTimer);if(tool==='select')ctx.putImageData(before,0,0);$('.paint-status',status).textContent=tool==='select'?'Selection ready. Press Delete to clear it.':names[tool];}
canvas.onpointerup=end;canvas.onpointercancel=end;w.el.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();}if(e.key==='Delete'&&selection){snapshot();ctx.fillStyle=secondary;ctx.fillRect(selection.x,selection.y,selection.w,selection.h);selection=null;}});
menubar(w,{'File':[{label:'New',action:()=>dialog('Paint','<p>Start a new drawing?</p>',{buttons:[['New drawing',clear],['Cancel',null]]})},{label:'Save as PNG...',shortcut:'Ctrl+S',action:save},null,{label:'Exit',action:w.close}],'Edit':()=>[{label:'Undo',shortcut:'Ctrl+Z',disabled:!history.length,action:undo},{label:'Redo',shortcut:'Ctrl+Y',disabled:!future.length,action:redo}],'View':[{label:'Fit canvas to window',action:()=>$('.paint-scroll',w.body).classList.toggle('actual-size')}],'Image':[{label:'Clear image',action:clear},{label:'Invert colors',action:()=>{snapshot();const im=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<im.data.length;i+=4){im.data[i]=255-im.data[i];im.data[i+1]=255-im.data[i+1];im.data[i+2]=255-im.data[i+2];}ctx.putImageData(im,0,0);}}],'Help':[{label:'Help Topics',action:()=>dialog('Paint Help','<p>Pick a tool and color, then draw with your mouse, finger, or pen. Use Size to change the stroke. Fill colors enclosed areas; Text adds a caption.</p><p>Right-click a palette color to change the background / eraser color. Use Edit → Undo to step back, or File → Save as PNG to keep your artwork.</p>')}]});w.cleanup=()=>clearInterval(sprayTimer);colors();}
