import {$,esc,icon,closeMenus,closeAll} from './ui.js';
let phase='desktop',animation=0,timers=[],started=0;const messages=[['Windows','This program has performed an illegal operation and will be shut down.'],['KERNEL32.DLL','Agent replication detected. The system cannot contain this process.'],['System Warning','There is no spoon. There is also no available memory.'],['Explorer','EXPLORER.EXE has stopped responding.'],['Agent Smith','Mr. Foster... we meet again.'],['Fatal Exception','Reality.sys could not be found.'],['Windows Protection Error','An agent has overwritten your desktop.'],['Out of Memory','Too many Smiths. Not enough RAM.']];
function storage(v){try{if(v)sessionStorage.setItem('win98-recovery',v);else sessionStorage.removeItem('win98-recovery');}catch{}}
function cleanup(){cancelAnimationFrame(animation);timers.forEach(clearTimeout);timers=[];}
export function getPhase(){return phase;}
export function launchSmith(){if(phase!=='desktop')return;phase='infecting';closeMenus();$('#desktop').setAttribute('inert','');$('#taskbar').setAttribute('inert','');const overlay=$('#overlay');overlay.className='takeover';overlay.innerHTML='<canvas class="matrix-rain" aria-hidden="true"></canvas><div class="corruption-dialogs" aria-hidden="true"></div><div class="smith-terminal"><div>C:\\WINDOWS&gt; agent_smith.exe</div><br><div>Initializing agent replication...</div><div>Wake up, Mr. Foster.</div><span class="terminal-cursor">_</span></div><button class="skip-sequence raised">Skip sequence</button><span class="sr-only" role="status">Agent Smith is taking over the desktop. A blue screen will follow.</span>';
$('.skip-sequence',overlay).onclick=showBSOD;$('.skip-sequence',overlay).focus();
const canvas=$('canvas',overlay),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let width=innerWidth,height=innerHeight;canvas.width=width;canvas.height=height;const cols=Math.ceil(width/18),drops=Array.from({length:cols},()=>-Math.random()*45),fronts=Array.from({length:cols},()=>Math.random()*.35),chars='ｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿ012345789ABCDEF:;<>[]';started=performance.now();let last=0,errorCount=0;
function draw(now){if(phase!=='infecting')return;const seconds=(now-started)/1000;if(now-last>65){last=now;const progress=Math.max(0,(seconds-1.5)/10);ctx.clearRect(0,0,width,height);for(let i=0;i<cols;i++){const eaten=Math.min(height,Math.max(0,(progress-fronts[i])*(height*1.6)));ctx.fillStyle='#000';ctx.fillRect(i*18,0,19,eaten);ctx.font='15px monospace';const head=(drops[i]*18)%(height+380);for(let t=0;t<18;t++){const y=head-t*18;if(y<0||y>height)continue;ctx.fillStyle=t===0?'#c0ffcf':`rgba(0,${230-t*7},55,${Math.max(.12,1-t/20)})`;ctx.fillText(chars[Math.floor(Math.random()*chars.length)],i*18,y);}drops[i]+=reduced?.3:1.2;}if(seconds>3)$('.smith-terminal',overlay)?.classList.add('corrupted');}animation=requestAnimationFrame(draw);}
function error(){if(phase!=='infecting')return;const box=document.createElement('div');box.className='error-popup raised';const [title,msg]=messages[errorCount%messages.length];const ww=Math.min(360,width-28);box.style.width=ww+'px';box.style.left=Math.max(6,((errorCount*137+width*.3)%(width-ww+1)))+'px';box.style.top=Math.max(6,((errorCount*91+80)%Math.max(40,height-210)))+'px';box.innerHTML=`<div class="titlebar"><span>${esc(title)}</span><span class="fake-close raised">×</span></div><div class="error-message"><span class="error-symbol">${errorCount%3?'!':'×'}</span><p>${esc(msg)}</p></div><div class="fake-ok raised">OK</div>`;const host=$('.corruption-dialogs',overlay);host.append(box);while(host.children.length>(reduced?3:10))host.firstElementChild.remove();errorCount++;timers.push(setTimeout(error,reduced?950:Math.max(145,760-errorCount*50)));}
if(!reduced)animation=requestAnimationFrame(draw);else{canvas.style.background='rgba(0,15,0,.7)';$('.smith-terminal',overlay).insertAdjacentHTML('beforeend','<p>Replicating agents...<br>Overwriting desktop...<br>System halted.</p>');}timers.push(setTimeout(error,1800));timers.push(setTimeout(showBSOD,reduced?6500:13500));}
export function showBSOD(){cleanup();phase='bsod';const overlay=$('#overlay');overlay.className='bsod';overlay.innerHTML='<div class="bsod-content"><span class="bsod-brand">Windows</span><p>A fatal exception 0E has occurred at 0028:C0011E36 in VXD AGENT_SMITH(01) + 00000A98. The current application will be terminated.</p><p>* Agent Smith has made himself at home in your operating system.<br>* Press Refresh page to attempt system recovery.<br>* Any unsaved work may be lost in the simulation.</p><p class="bsod-code">Error: TOO_MANY_SMITHS</p><button class="bsod-refresh">Refresh page</button><p class="bsod-prompt">Press ENTER to continue <span class="terminal-cursor">_</span></p><span class="bsod-parody">A Windows 98 parody. Your actual device is fine.</span></div>';$('.bsod-refresh',overlay).onclick=()=>{storage('recovery');showRecovery();};$('.bsod-refresh',overlay).focus();}
export function showRecovery(){cleanup();phase='recovery';storage('recovery');$('#desktop').setAttribute('inert','');$('#taskbar').setAttribute('inert','');const overlay=$('#overlay');overlay.className='recovery';overlay.innerHTML='<header class="recovery-header"><span class="recovery-monogram">KJF<span>®</span></span><span>SYSTEM RECOVERY</span></header><div class="recovery-body"><div class="recovery-label"><span></span> A NEW KIND OF OPERATING SYSTEM</div><h1>Your operating system has been infected with LLM Agents such as Agent Smith, please do not be afraid.</h1><p>Everything is still here. Let’s bring you back to familiar territory.</p><button class="destruct-button">Destruct all Agent Smiths <span aria-hidden="true">↗</span></button></div><footer class="recovery-footer"><span>Kurt J. Foster</span><span>1998 → '+new Date().getFullYear()+'</span></footer>';
$('.destruct-button',overlay).onclick=()=>{storage(null);phase='desktop';$('#desktop').removeAttribute('inert');$('#taskbar').removeAttribute('inert');overlay.className='';overlay.replaceChildren();closeAll();document.dispatchEvent(new CustomEvent('desktop-reset'));};$('.destruct-button',overlay).focus();}
export function restorePhase(){try{if(sessionStorage.getItem('win98-recovery')==='recovery')showRecovery();}catch{}}
document.addEventListener('keydown',e=>{if(phase==='bsod'&&e.key==='Enter'){e.preventDefault();showRecovery();}if(phase==='infecting'&&e.key==='Escape'){e.preventDefault();showBSOD();}});
