export const $=(q,root=document)=>root.querySelector(q);
export const $$=(q,root=document)=>[...root.querySelectorAll(q)];
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(name,size=32){return `<img class="pixel-icon" src="assets/icons/${({computer:"my-computer",globe:"zone-internet",executable:"task",display:"settings",file:"notepad-file"})[name]||name}-${size<=16?"16x16":"32x32"}.png" width="${size}" height="${size}" alt="" draggable="false">`;}
export function download(name,data,type='text/plain'){const url=typeof data==='string'&&data.startsWith('data:')?data:URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();if(url.startsWith('blob:'))setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function launchable(el,open,select=()=>{}){let touch=false;el.addEventListener('pointerdown',e=>{touch=e.pointerType==='touch'||e.pointerType==='pen';});el.addEventListener('click',()=>{select();if(touch||innerWidth<=600)open();});el.addEventListener('dblclick',()=>{if(!touch&&innerWidth>600)open();});el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();open();}if(e.key===' '){e.preventDefault();select();}});}
export const windows=new Map();let z=20;let active=null;let counter=0;
export function closeMenus(){$('#menus').replaceChildren();$('#start-button').classList.remove('pressed');}
export function menu(anchor,items,at){closeMenus();const m=document.createElement('div');m.className='popup-menu raised';m.setAttribute('role','menu');for(const item of items){if(!item){m.insertAdjacentHTML('beforeend','<div class="menu-separator"></div>');continue;}const b=document.createElement('button');b.setAttribute('role','menuitem');b.disabled=!!item.disabled;b.innerHTML=`<span class="menu-check">${item.checked?'✓':''}</span><span>${esc(item.label)}</span><span class="shortcut">${esc(item.shortcut||'')}</span>`;b.addEventListener('click',()=>{closeMenus();item.action?.();});m.append(b);}$('#menus').append(m);const r=anchor?.getBoundingClientRect();m.style.left=Math.min(at?.x??r.left,innerWidth-m.offsetWidth-4)+'px';m.style.top=Math.min(at?.y??r.bottom,innerHeight-42-m.offsetHeight)+'px';m.querySelector('button:not(:disabled)')?.focus();m.addEventListener('keydown',e=>{const list=$$('button:not(:disabled)',m),i=list.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();list[(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus();}if(e.key==='Escape'){closeMenus();anchor?.focus();}});return m;}
export function menubar(w,items){const nav=document.createElement('nav');nav.className='menubar';nav.setAttribute('aria-label',w.title+' menu');for(const [label,options] of Object.entries(items)){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-haspopup','menu');b.addEventListener('click',()=>menu(b,typeof options==='function'?options():options));nav.append(b);}w.el.insertBefore(nav,w.el.children[1]);return nav;}
function tasks(){const el=$('#tasks');el.replaceChildren();for(const w of windows.values()){const b=document.createElement('button');b.className='task-button '+(w.id===active&&!w.minimized?'sunken active':'raised');b.innerHTML=icon(w.icon,16)+`<span>${esc(w.title)}</span>`;b.title=w.title;b.setAttribute('aria-label','Switch to '+w.title);b.onclick=()=>{if(active===w.id&&!w.minimized)w.minimize();else w.focus();};el.append(b);}}
export function createWindow({id='window-'+(++counter),title,icon:ico='folder',width=680,height=450,x,y,className='',resizable=true}){if(windows.has(id)){const w=windows.get(id);w.focus();return w;}const el=document.createElement('section');el.className='window '+className;el.setAttribute('role','dialog');el.setAttribute('aria-label',title);el.tabIndex=-1;const offset=windows.size*24;
const w={id,title,icon:ico,el,minimized:false,maximized:false,body:document.createElement('div'),cleanup:null};
el.style.width=Math.min(width,innerWidth-12)+'px';el.style.height=Math.min(height,innerHeight-75)+'px';el.style.left=Math.max(6,Math.min(x??Math.max(115,(innerWidth-width)/2)+offset,innerWidth-Math.min(width,innerWidth-12)-6))+'px';el.style.top=Math.max(6,Math.min(y??Math.max(35,(innerHeight-height)/3)+offset,innerHeight-height-45))+'px';
el.innerHTML=`<header class="titlebar">${icon(ico,16)}<span class="window-title">${esc(title)}</span><div class="window-actions"><button class="raised minimize" aria-label="Minimize ${esc(title)}"><span>_</span></button><button class="raised maximize" aria-label="Maximize ${esc(title)}"><span class="max-symbol"></span></button><button class="raised close" aria-label="Close ${esc(title)}">×</button></div></header>`;
w.body.className='window-content';el.append(w.body);if(resizable){const grip=document.createElement('div');grip.className='resize-grip';grip.setAttribute('aria-hidden','true');el.append(grip);grip.onpointerdown=e=>{if(w.maximized)return;e.preventDefault();grip.setPointerCapture(e.pointerId);const r=el.getBoundingClientRect(),sx=e.clientX,sy=e.clientY;grip.onpointermove=ev=>{el.style.width=Math.max(Math.min(300,innerWidth-12),Math.min(innerWidth-r.left-4,r.width+ev.clientX-sx))+'px';el.style.height=Math.max(200,Math.min(innerHeight-42-r.top,r.height+ev.clientY-sy))+'px';};grip.onpointerup=()=>grip.onpointermove=null;};}
w.focus=()=>{w.minimized=false;el.hidden=false;active=id;el.style.zIndex=++z;for(const o of windows.values())o.el.classList.toggle('inactive',o.id!==id);tasks();};
w.close=()=>{w.cleanup?.();el.remove();windows.delete(id);closeMenus();const next=[...windows.values()].filter(o=>!o.minimized).sort((a,b)=>+b.el.style.zIndex-+a.el.style.zIndex)[0];if(next)next.focus();else{active=null;tasks();$('#desktop-icons button')?.focus();}};
w.minimize=()=>{w.minimized=true;el.hidden=true;active=null;const next=[...windows.values()].filter(o=>!o.minimized&&o.id!==id).sort((a,b)=>+b.el.style.zIndex-+a.el.style.zIndex)[0];if(next)next.focus();else tasks();};
w.maximize=()=>{if(!resizable)return;w.maximized=!w.maximized;el.classList.toggle('maximized',w.maximized);$('.maximize',el).setAttribute('aria-label',(w.maximized?'Restore ':'Maximize ')+w.title);};
w.setTitle=t=>{w.title=t;const nav=$('.menubar',el);if(nav)nav.setAttribute('aria-label',t+' menu');$('.window-title',el).textContent=t;el.setAttribute('aria-label',t);for(const act of ['minimize','maximize','close'])$('.'+act,el).setAttribute('aria-label',act[0].toUpperCase()+act.slice(1)+' '+t);tasks();};
$('.minimize',el).onclick=w.minimize;$('.close',el).onclick=w.close;$('.maximize',el).onclick=w.maximize;if(!resizable)$('.maximize',el).disabled=true;
el.addEventListener('pointerdown',()=>w.focus(),{capture:true});const bar=$('.titlebar',el);bar.ondblclick=e=>{if(!e.target.closest('button'))w.maximize();};bar.onpointerdown=e=>{if(e.target.closest('button')||w.maximized||innerWidth<600)return;e.preventDefault();bar.setPointerCapture(e.pointerId);const r=el.getBoundingClientRect(),sx=e.clientX,sy=e.clientY;bar.onpointermove=ev=>{el.style.left=Math.max(0,Math.min(innerWidth-r.width,r.left+ev.clientX-sx))+'px';el.style.top=Math.max(0,Math.min(innerHeight-78,r.top+ev.clientY-sy))+'px';};bar.onpointerup=()=>bar.onpointermove=null;};
$('#windows').append(el);windows.set(id,w);w.focus();document.dispatchEvent(new Event('win98-open'));return w;}
export function dialog(title,body,{icon:ico='computer',buttons=[['OK',null]],width=420}={}){const w=createWindow({title,icon:ico,width,height:240,className:'message-window',resizable:false});w.body.innerHTML=`<div class="message-content">${icon(ico)}<div>${body}</div></div><div class="dialog-buttons"></div>`;const actions=$('.dialog-buttons',w.body);for(const [label,fn] of buttons){const b=document.createElement('button');b.className='raised standard-button';b.textContent=label;b.onclick=()=>{w.close();fn?.();};actions.append(b);}actions.querySelector('button')?.focus();return w;}
export function statusbar(w,html){const el=document.createElement('footer');el.className='statusbar';el.innerHTML=html;w.el.append(el);return el;}
export function closeAll(){for(const w of [...windows.values()])w.close();}
export function showDesktop(){const shown=[...windows.values()].some(w=>!w.minimized);for(const w of windows.values()){w.minimized=shown;w.el.hidden=shown;}active=null;tasks();if(!shown)[...windows.values()].at(-1)?.focus();}
export function currentWindow(){return windows.get(active);}
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#menus,.menubar,#start-button'))closeMenus();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenus();if(e.altKey&&e.key==='F4'){e.preventDefault();currentWindow()?.close();}});
addEventListener('resize',()=>{if(innerWidth<600)return;for(const w of windows.values()){if(w.maximized)continue;const r=w.el.getBoundingClientRect();w.el.style.left=Math.max(4,Math.min(r.left,innerWidth-r.width-4))+'px';w.el.style.top=Math.max(4,Math.min(r.top,innerHeight-100))+'px';}});
